### PR TITLE
Dashboard edit

### PR DESCRIPTION
**Pull request by daemonl**
Sort the resources in the HTML resource response so that failed, progressing and recent containers are on top (i.e. visible in a dashboard with limited space)

### CODE REVIEW

**Comment by daemonl** [comment]
Circle error, unlikely to be caused by this change
```
k8s_1  | failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
```

**Comment by daemonl** [comment]
I... wait... what? When... was that always there?!

**Comment by peterstace** [comment]
From memory I think it was added in Go 1.9, so a pretty recent addition.

**Comment by daemonl** [comment]
Closing PR to de-link from my account, the branch should still exist etc so you will be able to re-create.

**Pull request closed without merging**
